
include ..\Makefile.inc

EFLAGS = -I .. -pz .. -warn_all

OUTDIR = ..
BEAMS = ..\ejabberd_zlib.beam

SOURCE = 
OBJECT = 
DLL    = 

ALL : $(DLL) $(BEAMS)

CLEAN :
	-@erase $(DLL)
	-@erase $(OBJECT)
	-@erase $(BEAMS)

$(OUTDIR)\ejabberd_zlib.beam : ejabberd_zlib.erl
	erlc -W $(EFLAGS) -o $(OUTDIR) ejabberd_zlib.erl

CC=
CC_FLAGS=

LD=
LD_FLAGS=-

$(DLL) : $(OBJECT)
	$(LD) $(LD_FLAGS) -out:$@ $<

$(OBJECT) : $(SOURCE)
	$(CC) $(CC_FLAGS) -c -Fo$@ $<

